### ISSUE TITLE
description html αρχείων Γ φάσης

### ISSUE THREAD

**Issue by kbokis** [pdp-archive/pdp-archive.github.io#56]
(Ακυρο, τυπογραφικό λάθος ήταν)

**Comment by kbokis** [comment]
Στο _layouts/solution.html έχει τη δημιουργία περιγραφης
```
{% if **task.stage == "c"** %}
  {% assign stage_name = "Γ' Φάση" %}
...
{% assign title = page.contest | append: " " | append: stage_name | append: ": " | append: **task.full_name** | append: " (" | append: page.codename | append: ") - Λύση" %}
```

Το ονομα το αντλει απο το _data/contests/XX-PDP.yml
π.χ
```
loutraki: 
   full_name: "Λουτράκι"
   stage: "c"
   statement_pdf_url: "https://drive.google.com/open?id=1_7Kh1_4VfkyaiAPpQBaAVY8yVLgM0z_-"
   statement_md: true
   testcases_url: "https://drive.google.com/open?id=1zYZhAYENDWhJbami8vq33BPrk_GkwetE"
   solution: true
   solution_author: "Κωνσταντίνος Μποκής"
   codes_in_git: true
   points: 30

minpali: 
   full_name: "Παλίνδρομο"
```
και παιρνει την πρωτη επιλογη.
Μήπως πρέπει να βάλουμε στο yml εκτος απο τη φαση και αριθμο προβλήματος; Εναλλακτικα θα μπορουσαμε να βάλουμε στο stage:c1,c2,c3 αλλα χαλά την κανονικοποιηση (πάμε για BCNF normalization :) )
